// <auto-generated />
using System;
using ChairElections.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChairElectionNominations.Migrations
{
    [DbContext(typeof(CommitteeContext))]
    [Migration("20251217161829_chairStatements2")]
    partial class chairStatements2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ChairElections.Models.ChairNomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitteeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NominatedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NominationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NominationSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("NomineeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisteredInterest")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChairNominations");
                });

            modelBuilder.Entity("ChairElections.Models.ChairStatement", b =>
                {
                    b.Property<int>("ChairStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChairStatementText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitteeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChairStatementId");

                    b.ToTable("ChairStatements");
                });

            modelBuilder.Entity("ChairElections.Models.Committee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedParty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentChairId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("ChairElections.Models.RegisteredInterest", b =>
                {
                    b.Property<int>("RegisteredInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitteeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisteredInterestText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegisteredInterestId");

                    b.ToTable("RegisteredInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
